### ISSUE TITLE
Support for meta constraints.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#16]
We might want to have a field ask for either constraint A or constraint B.

How might we want to do that?

```yaml
fields:
    MyField:
        constraints:
            - type: either
              constraints:
                - type: User
                - type: Activity
models:
    User:
    Activity:
```
