### ISSUE TITLE
Find circular dependencies.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#17]
We need to make sure we cover below case:

```yaml
fields:
    A:
        constraints:
            - type: A
```
