### ISSUE TITLE
Fix the bug where inheriting from an incomplete model would result in partial inheritance.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#26]
Here's an example:

```yaml
fields:
    ReferToFutureModel:
        type: Model3

models:
    Model1:
        fields:
            test: ReferToFutureModel

    Model2:
        inherit: [Model1]

    Model3:
        fields:
            something:
```

Under this example, Model2 must have test but it would not under the current code.
