### ISSUE TITLE
Field to support custom messages.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#44]
# Expand meta attributes for Field

Currently, a field is only a collection of constraints.

This is to remain the same. However, we might benefit from allowing a few attributes that would go along with
FieldConstriant. Like a custom message.

```yaml
fields:
    SomeField:
        message: Incorrect value.
        break: true
        constraints:
            - type: regex
              pattern: \d{1,5}
```
