### ISSUE TITLE
Consider an "all" constraint to simplify using multiple constraints.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#45]
Consider this

```yaml
fields:
    List<Name>:
        constraints:
            type: list
            of:
                type: all
                items:
                    - string
                    - type: range
                      min: 10
                      max: 20
```
