### ISSUE TITLE
Create a dictionary constraint.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#46]
```yaml
fields:
    NameMap:
        constraints:
            - type: dict
              key: string
              value: integer
```
