### ISSUE TITLE
Add object/table constraint, or extent map constraint to read partial objects.

### ISSUE THREAD

**Issue by peymanmortazavi** [peymanmortazavi/garlic-models#64]
# Partial Objects

```yaml
fields:
    SomeField:
        constraints:
            - type: table
              keys:
                type: string
                name: string?
```

Determine the best way to accomplish this ability. Maybe not this constraint particularly, maybe not allowing optional
fields. But we need this somehow.
